# Demostrar el centro de masa de un triángulo cuyos vértices son ABC tienen como vectores posición a,b y c 
# pespectivamente y relativos a un origen común O. Demuestre que el vector posición g del centróide G del 
# triángulo viene dado por: 
# g = (a+b+c)/3

Ahora, debido a que los vectores de posición a,b,c tienen un mismo origen común, es necesario definir los vectores que son 
los lados del triángulo. 
Para ello definimos: 

# BA = OA - OB
# BC = OC - OB
# AC = OC - OA 

Es decir, decimos que OA = a, OB = b, OC = c.

Para hallar el centróide del triángulo se requiere: 
1. Hallar los puntos medios de cada lado 
2. Trazar las rectas que unen los vértices con el punto medio del lado contrario. 

En este caso, siendo un problema vectorial (Los vectores previamente definidos están todos en notación vectorial), escalamos los vectores de los lados por:
# a = 1/2

Es decir

# BM = aBC = 1/2 * BC = 1/2 * (OC - OB)
# BP = aBA = 1/2 * BA = 1/2 * (OA - OB)
# AN = aAC = 1/2 * AC = 1/2 * (OC - OA)

Y las medianas son (lo queremos demostrar) concurrentes en un mismo punto que llamaremos G. 

Para esto, partimos de definir los puntos medios, entonces: 

# BC = m
# BA = p
# AC = n

Siendo m,p,n los puntos medios. 

Decimos que entonces los vectores del punto medio son:

# BG = alphaBN (BN es el vector que va desde el vértice B hasta el punto medio de AC y así con todos)
# CG = uCP 
# AG = rAM

Y aquí es trabajar vectorialmente para hallar las operaciones necesarias para despejar

# BG = alphaBN = alpha(BC + CN) = alpha(c-b-0.5(c-a)) = alpha(c/2 + a/2 - b)
# CG = uCP = u(CA + AP) = U(a - c -0.5(a-b)) = u(a/2 + b/2 - c)
# AG = rAM = r(AB + BM) = r(b - a +1/2 (c-b)) = r(a/2 + b/2 -c)

Recordamos que por las propiedades del centroide, alpha, u, y r deben ser iguales. 

También 

# AG = AB + BG = b - a + alpha(c/2 + a/2 - b) = b - a + alphac/2 + alphaa/2 - alphab/2 


In [42]:
import numpy as np
import sympy as sym
import math

# PROBLEMA 2

In [41]:
#Dados los vectores 

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([3,2,1])
d = np.array([6,5,4])

#Encuentre

#a. 
l1 = a + b + c + d
print(l1)
#a2. 
l2 = a + b - c - d
print(l2)
#a3.
l3 = a - b + c - d
#a4.
l4 = (-1*a) + b - c + d
print(l4)

# Ángulo entre los vectores a,b,c,d y los vectores base e1,e2,e3 (Partiendo de la base canónica de R la cuál es ortonormal)
# Sabemos que u.v = |u||v|cos(O), despejamos, O = arc cos(u.v/|u||v|)

#Modulos 

aMOD = np.linalg.norm(a)
print(aMOD)
bMOD = np.linalg.norm(b)
cMOD = np.linalg.norm(c)
dMOD = np.linalg.norm(d)

#Angulos

Aab = math.acos((np.dot(a,b))/(aMOD * bMOD)) #y en grados
def degree(c):
    degval = (c * 180) / (math.pi)
    return degval

AabDeg = degree(Aab)
print(AabDeg)
Aac = math.acos((np.dot(a,c))/(aMOD * cMOD))
Aad = math.acos((np.dot(a,d))/(aMOD * dMOD))
Abc = math.acos((np.dot(b,c))/(bMOD * cMOD))
Abd = math.acos((np.dot(b,c))/(bMOD * dMOD))
Acd = math.acos((np.dot(c,d))/(cMOD * dMOD))

#c. La magnitud de los vectores (Ya se halló)
#d. El ángulo entre los vectores (Ya se halló)
#e. Proyeccion de a sobre b 

proyab = (np.dot(a,b) / (bMOD**2)) * b
print(proyab)

#Son los vectores a,b,c,d coplanares? Hay varias formas de responder esta pregunta. Siendo 4 vectores de tres componentes NO podemos
#usar el determinante sin embargo, podemos usar el rango de la matriz. 

A = np.array([a,b,c,d])
AT = np.transpose(A)
print(AT)
#Hallamos el rango 

ATrank = np.linalg.matrix_rank(AT)
print(ATrank) #---> Nos dio rango 2, es decir, dos vectores resultan como la combinación lineal de los otros. Es decir, de los 4 vectores
# dos de ellos son linealmente independientes y 2 de ellos resulta de las combinaciones lineales de los demás. 

#Otra forma de resolver el problema es con el sistema de ecuaciones lineales de la forma Ax = b con b = 0 

#g

opG = np.dot((a+b),(c+d))
print(opG)

#h. Los productos a x b, b x c, c x d y los angulos que forman con d. 

abcross = np.cross(a,b)
abcrossMOD = np.linalg.norm(abcross)
bccross = np.cross(b,c)
bccrossMOD = np.linalg.norm(bccross)
cdcross = np.cross(c,b)
cdcrossMOD = np.linalg.norm(cdcross)

# Y los ángulos son:
AbcrossD = math.acos((np.dot(abcross,d))/(abcrossMOD * dMOD))
BccrossD = math.acos((np.dot(bccross,d))/(bccrossMOD * dMOD))
CdcrossD = math.acos((np.dot(cdcross,d))/(cdcrossMOD * dMOD))

print(CdcrossD)

#i. 

opI = np.dot(c,(abcross))
print(opI)



[14 14 14]
[-4  0  4]
[6 6 6]
3.7416573867739413
12.933154491899135
[1.66233766 2.07792208 2.49350649]
[[1 4 3 6]
 [2 5 2 5]
 [3 6 1 4]]
2
139
1.5707963267948966
0


13. Dado el campo de fuerza: 

In [54]:
import math 
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt

#x =sym.Symbol('x')
#y =sym.Symbol('y')

#Introducimos los vectores base de R2

#i = np.array([1,0])
#j = np.array([0,1])


#funccar = -(1*y)/((x**2 + y**2)) + (x/(x**2 + y**2))

#Calcule el trabajo hecho en contra de este campo de fuerza al moverse al rededor de un circulo de radio uno y en el plano x - y
#Es decir, la integral de la fuerza por la distancia. 

#a. Desde 0 a pi en sentido contrario a las agujas del reloj 
#b. Desde 0 a -pi en sentido de las agujas 

#Parametrizamos la trayectoria 
'''
r = 1

w = sym.Symbol('w')
xp = r * math.cos(w) # math.cos(w)
yp = r * math.sin(w) # math.sin(w)
#Parametrizamos la trayectoria en coordenadas polares

#Aquí tenemos que reemplazar la fuerza por nuestra parametrización. 

parfunc = (-1* yp )/(xp**2 + yp**2) + (xp/(xp**2 + yp**2))
'''
#Reemplazando en la expresión los parámetros:

def F(x, y):
    return -sym.sin(y) * sym.I + sym.cos(x) * sym.I

#eSTA ES LA FUNCIÓN CON LA QUE SE DEBE TRABAJAR

#Definir radio e intervalos


t = sym.symbols('t')
dt = sym.symbols('dt')

r = 1
t_min = 0
t_max = sym.pi

x = sym.cos(t)
y = sym.sin(t)

# Calculamos el elemento de arco
ds = dt

# Integramos en el intervalo de integración
F_parametrizada = F(x, y) * ds
integral = sym.integrate(F_parametrizada, (t, t_min, t_max))

# Simplificamos la expresión
integral = sym.simplify(integral)

# Evaluamos la integral numéricamente
valor_numerico = sym.N(integral)

# Imprimimos el resultado
print("El valor de la integral de línea es:", integral)
print("El valor numérico de la integral de línea es:", valor_numerico)













El valor de la integral de línea es: I*dt*(-Integral(sin(sin(t)), (t, 0, pi)) + Integral(cos(cos(t)), (t, 0, pi)))
El valor numérico de la integral de línea es: I*dt*(-Integral(sin(sin(t)), (t, 0, pi)) + Integral(cos(cos(t)), (t, 0, pi)))


In [ ]:
#